### ISSUE TITLE
Device Info eror: Error: timeout of 5000ms exceeded

### ISSUE THREAD

**Issue by sanhuoO** [grzegorz914/homebridge-tasmota-control#3]
Hi, 
I hava 3 devices,like name A,B,C
devices are  random error  blow when i restart the homebridge
after waiting for a long time, is still error

---------------------
Node.js v16.14.2
Npm  v6.14.15
homebridge v1.4.0 
---------------------
Device: 192.168.1.26 A , Device Info eror: Error: timeout of 5000ms exceeded
    at createError (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:526:28)
    at Timeout.<anonymous> (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  config: [Object],
  code: 'ECONNABORTED',
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, state: Offline, trying to reconnect

**Comment by grzegorz914** [comment]
Is the device reachable on this address? 
What a device is it?

**Comment by sanhuoO** [comment]
there ar sonoff devices  with Tasmota 11.0.0.3 
and i try to change 5000 to 15000 looks well down
thank you
    this.axiosInstance = axios.create({
      method: 'GET',
      baseURL: url,
      timeout: 15000
    });

**Comment by sanhuoO** [comment]
oh man its back again
"POWER": "ON"
}
[4/15/2022, 10:52:38 PM] [tasmotaControl] Device: 192.168.1.30 客厅, Device Info eror: Error: timeout of 15000ms exceeded
    at createError (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:526:28)
    at Timeout.<anonymous> (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  config: [Object],
  code: 'ECONNABORTED',
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}, state: Offline, trying to reconnect
[4/15/2022, 10:52:43 PM] [tasmotaControl] Device: 192.168.1.26 饮水机, debug response: {
  "POWER": "ON"
}
[4/15/2022, 10:52:44 PM] [tasmotaControl] Device: 192.168.1.17 厕所, debug response: {
  "POWER": "ON"
}
[4/15/2022, 10:52:48 PM] [tasmotaControl] Device: 192.168.1.30 客厅, Device Info eror: Error: timeout of 15000ms exceeded
    at createError (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:526:28)
    at Timeout.<anonymous> (/volume1/@appdata/homebridge/lib/node_modules/homebridge-tasmota-control/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  config: [Object],

**Comment by grzegorz914** [comment]
Probably your device loses the connection to the network, it has nothing to do direct with this plugin. Check your network environment please.
